language: android
jdk: oraclejdk7
env:
  matrix:
  - ANDROID_SDKS=android-21 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
  global:
  - secure: Yg5HqPd150G4LnXk5Wb3SrkAVthOW5NiUenBSf+pqugGAXkCShZ37E70Zyp7ui+NIYmYzOQ7hdXHVxKx3tv+XM23XekcVhVkes1z0P1uKpItIMsC6HwaZEH1bEsE9do0y8twtS63Tf4dAW8hz8wDF/0s/qu+S9APfAgmxrJFNNg=
  - secure: CUJefuYqqBxbggV83polXcVJ1XWgLdfRB9AhVoLOs+uYoa11wfzkwM0aFb0KOCORtdUKNDsHetXtoDfu/yH9sGMqTuYJUnzzHMWme8fuaYzZb0U/WuksOrbSK+LnuHqEiENATSLUBGAK37JUlCFnaU/p1+RoH5wt5bSMl6FMus8=
android:
  components:
  - platform-tools
  - tools
  - build-tools-21.1.1
#before_install:
#- sudo apt-get update -qq
#- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
#- wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
#- tar xzf android-sdk_r21.0.1-linux.tgz
#- export ANDROID_HOME=$PWD/android-sdk-linux
#- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
#- echo y | android update sdk --filter 18,19,21,22,24 --no-ui --force
#- find ~ -name "android-sdk-linux" -ls
before_script:
- wget http://services.gradle.org/distributions/gradle-2.2-bin.zip
- unzip gradle-2.2-bin.zip
- export GRADLE_HOME=$PWD/gradle-2.2
- export PATH=$GRADLE_HOME/bin:$PATH
- sudo find / -name "zipalign" -ls
script: gradle assemble
before_deploy:
- git config --global user.email "hqlgree2@gmail.com"
- git config --global user.name "hqlgree2_ci"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "auto release from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://github.com/gree2/EasternPioneerBus --tags
- export APK_FN=EasternPioneerBus-0.1.$TRAVIS_BUILD_NUMBER
- mv ./app/build/outputs/apk/app-release-unsigned.apk ./${APK_FN}-unaligned.apk
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -tsa http://timestamp.digicert.com -keystore epb.keystore -storepass $STOREPASS ./${APK_FN}-unaligned.apk epb
- zipalign -v 4 ./${APK_FN}-unaligned.apk ./${APK_FN}.apk
deploy:
  api-key:
    secure: dh9Ei+jKIyRRZ6iC6X5FvlAvElxJFieRVDbvr9c09hNZmz0HT9Tay3q66bqa3p7XGZUA9hRPUW3hVnX/vTJzwmEkYZMd5ehTi7Cmjg8gIFl3cs7fBkHMJ6fivyCYw8X/AbPLxQzsSeQh74n09a8cXbFg6z/GPgTsRUO2YDVgon0=
  provider: releases
  file: "./${APK_FN}.apk"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
branches:
  except:
  - "/^*-v[0-9]/"
