language: android
jdk: oraclejdk7
env:
  matrix:
  - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
android:
  components:
  - build-tools-21.1.1
before_script:
- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
- emulator -avd test -no-skin -no-audio -no-window &
- adb wait-for-device
- adb shell input keyevent 82 &
- wget http://services.gradle.org/distributions/gradle-2.2-bin.zip
- unzip gradle-2.2-bin.zip
- export GRADLE_HOME=$PWD/gradle-2.2
- export PATH=$GRADLE_HOME/bin:$PATH
script: gradle assemble
deploy:
  api-key:
    secure: dh9Ei+jKIyRRZ6iC6X5FvlAvElxJFieRVDbvr9c09hNZmz0HT9Tay3q66bqa3p7XGZUA9hRPUW3hVnX/vTJzwmEkYZMd5ehTi7Cmjg8gIFl3cs7fBkHMJ6fivyCYw8X/AbPLxQzsSeQh74n09a8cXbFg6z/GPgTsRUO2YDVgon0=
  provider: releases
  file: "app-debug.apk"
  skip_cleanup: true
  on:
    tags: true