# language: android
# android:
#   components:
#     # - sys-img-x86-android-17
#     - build-tools-21.1.1
#     - android-15
#     - android-21

language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-21.1.1

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
  # Gradle
  - wget http://services.gradle.org/distributions/gradle-2.0-bin.zip
  - unzip gradle-2.0-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.0
  - export PATH=$GRADLE_HOME/bin:$PATH

script: gradle assemble