package com.hql.gree2.easternpioneerbus.dao;

import java.util.List;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table BUS_LINE.
 */
public class BusLine {

    private Long id;
    private Integer lineIndex;
    private String lineName;
    private String lineCode;
    private Boolean lineSync;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient BusLineDao myDao;

    private List<BusStop> busStops;

    public BusLine() {
    }

    public BusLine(Long id) {
        this.id = id;
    }

    public BusLine(Long id, Integer lineIndex, String lineName, String lineCode, Boolean lineSync) {
        this.id = id;
        this.lineIndex = lineIndex;
        this.lineName = lineName;
        this.lineCode = lineCode;
        this.lineSync = lineSync;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getBusLineDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getLineIndex() {
        return lineIndex;
    }

    public void setLineIndex(Integer lineIndex) {
        this.lineIndex = lineIndex;
    }

    public String getLineName() {
        return lineName;
    }

    public void setLineName(String lineName) {
        this.lineName = lineName;
    }

    public String getLineCode() {
        return lineCode;
    }

    public void setLineCode(String lineCode) {
        this.lineCode = lineCode;
    }

    public Boolean getLineSync() {
        return lineSync;
    }

    public void setLineSync(Boolean lineSync) {
        this.lineSync = lineSync;
    }

    /**
     * To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity.
     */
    public List<BusStop> getBusStops() {
        if (busStops == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BusStopDao targetDao = daoSession.getBusStopDao();
            List<BusStop> busStopsNew = targetDao._queryBusLine_BusStops(id);
            synchronized (this) {
                if (busStops == null) {
                    busStops = busStopsNew;
                }
            }
        }
        return busStops;
    }

    /**
     * Resets a to-many relationship, making the next get call to query for a fresh result.
     */
    public synchronized void resetBusStops() {
        busStops = null;
    }

    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

}
