package com.hql.gree2.easternpioneerbus.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table BUS_STOP_IMAGE.
 */
public class BusStopImageDao extends AbstractDao<BusStopImage, Long> {

    public static final String TABLENAME = "BUS_STOP_IMAGE";

    /**
     * Properties of entity BusStopImage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BusStopId = new Property(1, long.class, "busStopId", false, "BUS_STOP_ID");
        public final static Property ImageIndex = new Property(2, Integer.class, "imageIndex", false, "IMAGE_INDEX");
        public final static Property ImageName = new Property(3, String.class, "imageName", false, "IMAGE_NAME");
    }

    ;

    private DaoSession daoSession;

    private Query<BusStopImage> busStop_BusStopImagesQuery;

    public BusStopImageDao(DaoConfig config) {
        super(config);
    }

    public BusStopImageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'BUS_STOP_IMAGE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'BUS_STOP_ID' INTEGER NOT NULL ," + // 1: busStopId
                "'IMAGE_INDEX' INTEGER," + // 2: imageIndex
                "'IMAGE_NAME' TEXT);"); // 3: imageName
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BUS_STOP_IMAGE'";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, BusStopImage entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getBusStopId());

        Integer imageIndex = entity.getImageIndex();
        if (imageIndex != null) {
            stmt.bindLong(3, imageIndex);
        }

        String imageName = entity.getImageName();
        if (imageName != null) {
            stmt.bindString(4, imageName);
        }
    }

    @Override
    protected void attachEntity(BusStopImage entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public BusStopImage readEntity(Cursor cursor, int offset) {
        BusStopImage entity = new BusStopImage( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.getLong(offset + 1), // busStopId
                cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // imageIndex
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // imageName
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, BusStopImage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBusStopId(cursor.getLong(offset + 1));
        entity.setImageIndex(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setImageName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(BusStopImage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(BusStopImage entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Internal query to resolve the "busStopImages" to-many relationship of BusStop.
     */
    public List<BusStopImage> _queryBusStop_BusStopImages(long busStopId) {
        synchronized (this) {
            if (busStop_BusStopImagesQuery == null) {
                QueryBuilder<BusStopImage> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.BusStopId.eq(null));
                busStop_BusStopImagesQuery = queryBuilder.build();
            }
        }
        Query<BusStopImage> query = busStop_BusStopImagesQuery.forCurrentThread();
        query.setParameter(0, busStopId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBusStopDao().getAllColumns());
            builder.append(" FROM BUS_STOP_IMAGE T");
            builder.append(" LEFT JOIN BUS_STOP T0 ON T.'BUS_STOP_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }

    protected BusStopImage loadCurrentDeep(Cursor cursor, boolean lock) {
        BusStopImage entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BusStop busStop = loadCurrentOther(daoSession.getBusStopDao(), cursor, offset);
        if (busStop != null) {
            entity.setBusStop(busStop);
        }

        return entity;
    }

    public BusStopImage loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();

        String[] keyArray = new String[]{key.toString()};
        Cursor cursor = db.rawQuery(sql, keyArray);

        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }

    /**
     * Reads all available rows from the given cursor and returns a list of new ImageTO objects.
     */
    public List<BusStopImage> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BusStopImage> list = new ArrayList<BusStopImage>(count);

        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }

    protected List<BusStopImage> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }


    /**
     * A raw-style query where you can pass any WHERE clause and arguments.
     */
    public List<BusStopImage> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }

}
