package com.hql.gree2.easternpioneerbus.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig busLineDaoConfig;
    private final DaoConfig busStopDaoConfig;
    private final DaoConfig busStopImageDaoConfig;

    private final BusLineDao busLineDao;
    private final BusStopDao busStopDao;
    private final BusStopImageDao busStopImageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        busLineDaoConfig = daoConfigMap.get(BusLineDao.class).clone();
        busLineDaoConfig.initIdentityScope(type);

        busStopDaoConfig = daoConfigMap.get(BusStopDao.class).clone();
        busStopDaoConfig.initIdentityScope(type);

        busStopImageDaoConfig = daoConfigMap.get(BusStopImageDao.class).clone();
        busStopImageDaoConfig.initIdentityScope(type);

        busLineDao = new BusLineDao(busLineDaoConfig, this);
        busStopDao = new BusStopDao(busStopDaoConfig, this);
        busStopImageDao = new BusStopImageDao(busStopImageDaoConfig, this);

        registerDao(BusLine.class, busLineDao);
        registerDao(BusStop.class, busStopDao);
        registerDao(BusStopImage.class, busStopImageDao);
    }

    public void clear() {
        busLineDaoConfig.getIdentityScope().clear();
        busStopDaoConfig.getIdentityScope().clear();
        busStopImageDaoConfig.getIdentityScope().clear();
    }

    public BusLineDao getBusLineDao() {
        return busLineDao;
    }

    public BusStopDao getBusStopDao() {
        return busStopDao;
    }

    public BusStopImageDao getBusStopImageDao() {
        return busStopImageDao;
    }

}
